name: .NET Core 3.1.302

# push on any branch / pull request to any branch
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      run: dotnet restore ./Uri.Tests
    - name: Build
      run: dotnet build --configuration Release --no-restore ./Uri.Tests
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./Uri.Tests
