name: Publish NuGet package

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, test, pack & publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Setup Python3
      uses: actions/setup-python@v2
      with:
        python-version: '3'
        architecture: 'x64'

    - name: Update version
      run: python .github/scripts/auto-increment-version.py

    - name: Commit version change
      run: |
        source .env
        git config user.name "Kamil Rusin"
        git config user.email "kamil.jakub.rusin@gmail.com"
        git add **/*.csproj
        git commit -m "Update version to ${URI_VERSION}"
        git tag -a ${URI_VERSION} -m "v${URI_VERSION}"

    - name: Install dependencies
      run: dotnet restore ./Uri
    - name: Build a Release version
      run: dotnet build --configuration Release --no-restore ./Uri
    - name: Run tests
      run: dotnet test --configuration Release --no-restore --no-build ./Uri.Tests
    - name: Pack
      run: dotnet pack --configuration Release -o out ./Uri --no-restore --no-build
    - name: Publish
      run: dotnet nuget push out/*.nupkg --api-key ${GITHUB_TOKEN} --source https://api.nuget.org/v3/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.URI_NUGET_KEY }}

    - name: Push commit & tag
      run: |
        git push origin
        git push origin --tags
